spring:
  datasource:
    url: jdbc:postgresql://ec2-3-209-61-239.compute-1.amazonaws.com:5432/d3pe8j6usn8gug
    username: pfvqwldvnvfrky
    password: e831a17ad570d8ae0ad24fbcfe8668ad9382dbf2a50f85b4d29232c1769d4734
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: '[0-9.a-zA-z_]^+$TutorAcademy989121233AAAAkjbgcNftrdrsdrsh^56444009unjbgGGGfd528482'